# Generated by Django 5.2.5 on 2025-09-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Tag must be 16 characters or less.'}, max_length=16),
        ),
    ]
